### ISSUE TITLE
v2.3 -- SDXL not working in MacBook Air M1 8GB

### ISSUE THREAD

**Issue by mikestreed** [divamgupta/diffusionbee-stable-diffusion-ui#485]
Maybe this is just due to lack of RAM and it's impossible to use SDXL on this machine, but thought I'd mention anyway, after having tried the new pre-release version 2.3 of DiffusionBee.

Screenshot of error below:

<img width="267" alt="Screenshot 2023-12-18 at 20 12 42" src="https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/143605829/e0bd9f6a-5ec6-4169-a6c5-8491f5a1a2b4">

**Comment by divamgupta** [comment]
What’s your OS version?

**Comment by mikestreed** [comment]
12.6 monterey

**Comment by divamgupta** [comment]
it should be fixed in the latest release. Could you try the latest 2.4 release, and let me know

**Comment by mikestreed** [comment]
OK thanks! Yeah the base model works great now, installed via the download button. Note that locally installed XL models still dont work... I think it's failing to convert to TDICT.
<img width="1632" alt="Screenshot 2023-12-29 at 14 08 08" src="https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/143605829/be39aef6-6c4d-42e8-ac62-72620c0040e6">
